version: "3.8"
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      # Ensure python output is sent immediately (for logging)
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net: # Isolated network that allow containers to communicate
    ipam: # IP Address Management settings, used to configure the network
      driver: default # Use default IPAM driver to manage IP addresses
      config:
        - subnet: 172.25.125.0/24
